blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import django.contrib.auth.views

urlpatterns = [
    url(r'', include('mblog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', django.contrib.auth.views.login, name = 'login')
]

mblog/urls.py
from django.conf.urls import url
from . import views
app_name= 'mblog'
urlpatterns = [
	url(r'^$', views.post_list, name = 'post_list'),
	url(r'^post/(?P<post_id>\d+)/$', views.post_detail, name = 'post_detail'),
	url(r'^post/new/$', views.post_new, name = 'post_new'),
	url(r'^post/(?P<post_id>\d+)/edit/$', views.post_edit, name = 'post_edit'),
	url(r'^drafts/', views.post_draft_list, name = 'post_draft_list'),
	url(r'^post/(?P<post_id>\d+)/publish/$', views.post_publish, name = 'post_publish'),
	url(r'^post/(?P<post_id>\d+)/delete/$', views.post_delete, name = 'post_delete'),
	url(r'^post/(?P<post_id>\d+)/comment/$', views.add_comment_to_post, name = 'add_comment_to_post'),
]

mblog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length = 200)
	text = models.TextField()
	created_date = models.DateTimeField(default = timezone.now())
	published_date = models.DateTimeField(blank = True, null = True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()
		
	def __str__(self):
		return self.title

class Comments(models.Model):
	post = models.ForeignKey('mblog.Post', related_name = 'comments')
	author = models.CharField(max_length = 200)
	text = models.TextField()
	created_date = models.DateTimeField(default = timezone.now())
	approved_comment = models.BooleanField(default = False)

	def approve(self):
		self.approved_comment = True
		self.save()

	def __str__(self):
		return self.text

mblog/forms.py
from django import forms
from .models import Post, Comments

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'text')

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comments
		fields = ('author', 'text')
		

mblog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post, Comments
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def post_list(request):
	print(request.method)
	posts = Post.objects.filter(published_date__lte = timezone.now()).order_by('published_date')
	return render(request, 'mblog/post_list.html', {'post':posts})

def post_detail(request, post_id):
	post = get_object_or_404(Post, pk = post_id)
	return render(request, 'mblog/post_detail.html', {'post': post})

@login_required
def post_new(request):
	print(request.path)
	if request.method == 'POST':
		form = PostForm(request.POST)
		if form.is_valid():
			new_post = form.save(commit = False)
			new_post.author = request.user
			# post.published_date = timezone.now()
			new_post.save()
			return redirect('mblog:post_detail', post_id = new_post.id)
	else:
		form = PostForm()
		return render(request, 'mblog/post_edit.html', {'form': form})

@login_required
def post_edit(request, post_id):
	existing_post = get_object_or_404(Post, pk = post_id)
	if request.method == 'POST':
		print(request.POST)
		form = PostForm(request.POST, instance = existing_post)
		if form.is_valid():
			updated_post = form.save(commit = False)
			updated_post.author = request.user
			# updated_post.published_date = timezone.now()
			updated_post.save()
			return redirect('mblog:post_detail', post_id = updated_post.id)
	else:
		form = PostForm(instance = existing_post)
		return render(request, 'mblog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
	draft_posts = Post.objects.filter(published_date__isnull = True).order_by('created_date')
	return render(request, 'mblog/post_draft_list.html', {'draft_posts': draft_posts})

@login_required
def post_publish(request, post_id):
	post = get_object_or_404(Post, pk = post_id)
	post.published_date = timezone.now()
	post.save()
	return redirect('mblog:post_detail', post_id = post_id)

@login_required
def post_delete(request, post_id):
	post = get_object_or_404(Post, pk = post_id)
	post.delete()
	return redirect('mblog:post_list')

def add_comment_to_post(request, post_id):
	post = get_object_or_404(Post, pk = post_id)
	if request.Method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit = False)
			comment.post = post
			comment.save()
			return redirect('mblog:post_detail', post_id = post_id)
	else:
		form = CommentForm()
		return render(request, 'mblog/add_comment_to_post.html', {'form': form})

mblog/templates/mblog/add_comment_to_post.html
{% extends 'mblog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

mblog/templates/mblog/base.html
{% load static %}
<html>
	<head>
		<title>Tianyao's blog</title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'mblog/mblog_base.css' %}">
	</head>
	<body>
		<div class="page-header">
			{% if request.user.is_authenticated%}
				<a href="{% url 'mblog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
				<a href="{% url 'mblog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>  
			{% else %}
				<a href="{% url 'login' %}"  class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
			{% endif %}
			<h1><a href="/">Tianyao's Blog</a></h1>
		</div>
		<div class="content container">
			<div class="row">
				<div class="col-md-8">
					{% block content %}
					{% endblock content%}
				</div>
			</div>
		</div>
	</body>
</html>

mblog/templates/mblog/post_detail.html
{% extends 'mblog/base.html' %}
{% block content %}
	<div class="post">
		{% if post.published_date %}
			<div class="date">
				{{ post.published_date }}
			</div>
		{% elif user.is_authenticated %}
			<a class="btn btn-default" href="{% url 'mblog:post_publish' post_id=post.id %}">Publish</a>
		{% endif %}
		{% if user.is_authenticated %}
			<a class="btn btn-default" href="{% url 'mblog:post_edit' post_id=post.id %}"><span class="glyphicon glyphicon-pencil"></sp an></a>
			<a class="btn btn-default" href="{% url 'mblog:post_delete' post_id=post.id %}"><span class="glyphicon glyphicon-remove"></sp an></a>
		{% endif %}
		<h1>{{ post.title }}</h1>
		<p>{{ post.text|linebreaksbr }}</p>
	</div>
	<hr>
	<a class="btn btn-default" href="{% url 'mblog:add_comment_to_post' post_id=post.id %}"></a>
	{% for comment in post.comments.all %}
		<div class="comment">
			<div class="date">{{ comment.created_date }}</div>
			<strong>{{ comment.author }}</strong>
			<p><{{ comment.text|linebreaks }}/p>
		</div>
	{% endfor %}
	 	<p>No comments yet: </p>
{% endblock %}

mblog/templates/mblog/post_draft_list.html
{% extends 'mblog/base.html' %}

{% block content %}
	{% for post in draft_posts %}
		<div class="post">
			<p class="data">created: {{ post.created_date|date:'d-m-Y'}}</p>
			<h1><a href="{% url 'mblog:post_detail' post_id=post.id %}">{{ post.title }}</a></h1>
			<p>{{ post.text|truncatewords:20}}</p>
		</div>
	{% endfor %}
{% endblock content %}

mblog/templates/mblog/post_edit.html
{% extends 'mblog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">
    	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

mblog/templates/mblog/post_list.html
{% extends 'mblog/base.html' %}
{%block content%}
	{% for post in post %}
		<div class="post">
			<div class="date">
				<p>published: {{ post.published_date }}</p>
			</div>
			<h1><a href="{% url 'mblog:post_detail' post_id=post.pk %}">{{ post.title }}</a></h1>
			<p>{{ post.text|linebreaksbr|truncatewords:20 }}</p>
			<a href="url 'mblog:post_detail' post_id=post.pk">Comments: {{ post.comments.count }}</a>
		</div>
	{% endfor %}
{%endblock%}